CREATE DATABASE IF NOT EXISTS meowmeow;

USE meowmeow;

CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    sap VARCHAR(9) NOT NULL,
    contact VARCHAR(15) NOT NULL
);
